import fs from 'node:fs/promises';
import { uploadFilePath } from '@/lib/uploads';

export const dynamic = 'force-dynamic';

const CONTENT_TYPES: Record<string, string> = {
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  png: 'image/png',
  webp: 'image/webp',
  gif: 'image/gif',
};

// Serves admin-uploaded images from data/uploads/ — see lib/uploads.ts for
// why this isn't just a public/uploads/ static file.
export async function GET(_request: Request, { params }: { params: Promise<{ filename: string }> }) {
  const { filename } = await params;

  // Reject path traversal / directory separators — filenames are always
  // generated by saveUploadedImage() as `${timestamp}-${hex}.${ext}`.
  if (!/^[a-zA-Z0-9_-]+\.[a-zA-Z0-9]+$/.test(filename)) {
    return new Response('Not found', { status: 404 });
  }

  const ext = filename.split('.').pop()?.toLowerCase() ?? '';
  const contentType = CONTENT_TYPES[ext];
  if (!contentType) {
    return new Response('Not found', { status: 404 });
  }

  try {
    const buffer = await fs.readFile(uploadFilePath(filename));
    return new Response(new Uint8Array(buffer), {
      headers: {
        'Content-Type': contentType,
        'Cache-Control': 'public, max-age=31536000, immutable',
      },
    });
  } catch {
    return new Response('Not found', { status: 404 });
  }
}
